version: 0.2

env:
  parameter-store:
    JWT_SECRET: "JWT_SECRET"

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - apt-get update -y
      - apt-get install -y python3-pip
      - echo Installing AWS CLI and kubectl...
      - pip3 install awscli
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-01/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin
  pre_build:
    commands:
      - echo Configuring AWS CLI...
      - aws eks update-kubeconfig --region us-west-2 --name linhnc4-eks-cluster
      - echo Installing Python dependencies...
      - pip3 install -r requirements.txt
      - echo Running tests...
      - python3 -m unittest discover -s tests
  build:
    commands:
      - echo "Building the application..."
      - echo "JWT_SECRET is $JWT_SECRET"
      - echo Building Docker image...
      - docker build -t my-docker-repo/my-app:latest .
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin linhnc4.dkr.ecr.us-west-2.amazonaws.com
      - echo Tagging Docker image...
      - docker tag my-docker-repo/my-app:latest linhnc4.dkr.ecr.us-west-2.amazonaws.com/my-app:latest
      - echo Pushing Docker image to ECR...
      - docker push linhnc4.dkr.ecr.us-west-2.amazonaws.com/my-app:latest

  post_build:
    commands:
      - echo Deploying to EKS...
      - kubectl apply -f k8s/deployment.yaml
      - kubectl apply -f k8s/service.yaml

artifacts:
  files:
    - '**/*'
